/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const Const_Colors = {
  green: "#00C950",
  yellow: "#FF6900",
  red: "#FB2C36",
};

export const Colors = {
  light: {
    primary: "#4E5C92",
    surfaceTint: "#4E5C92",
    onPrimary: "#FFFFFF",
    primaryContainer: "#DCE1FF",
    onPrimaryContainer: "#05164B",
    secondary: "#465D91",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#D9E2FF",
    onSecondaryContainer: "#001A43",
    tertiary: "#63568F",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#E8DEFF",
    onTertiaryContainer: "#1F1048",
    error: "#BA1A1A",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#410002",
    background: "#FAF8FF",
    onBackground: "#1A1B21",
    surface: "#F8F9FF",
    onSurface: "#191C20",
    surfaceVariant: "#E2E1EC",
    onSurfaceVariant: "#45464F",
    outline: "#767680",
    outlineVariant: "#C6C5D0",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#2E3035",
    inverseOnSurface: "#EFF0F7",
    inversePrimary: "#B7C4FF",
    primaryFixed: "#DCE1FF",
    onPrimaryFixed: "#05164B",
    primaryFixedDim: "#B7C4FF",
    onPrimaryFixedVariant: "#364479",
    secondaryFixed: "#D9E2FF",
    onSecondaryFixed: "#001A43",
    secondaryFixedDim: "#AFC6FF",
    onSecondaryFixedVariant: "#2D4678",
    tertiaryFixed: "#E8DEFF",
    onTertiaryFixed: "#1F1048",
    tertiaryFixedDim: "#CDBDFF",
    onTertiaryFixedVariant: "#4B3E76",
    surfaceDim: "#D8DAE0",
    surfaceBright: "#F8F9FF",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#F2F3FA",
    surfaceContainer: "#ECEEF4",
    surfaceContainerHigh: "#E7E8EE",
    surfaceContainerHighest: "#E1E2E8",
    green: Const_Colors.green,
    yellow: Const_Colors.yellow,
    red: Const_Colors.red,
  },
  dark: {
    primary: "#B7C4FF",
    surfaceTint: "#B7C4FF",
    onPrimary: "#1E2D61",
    primaryContainer: "#364479",
    onPrimaryContainer: "#DCE1FF",
    secondary: "#AFC6FF",
    onSecondary: "#132F60",
    secondaryContainer: "#2D4678",
    onSecondaryContainer: "#D9E2FF",
    tertiary: "#CDBDFF",
    onTertiary: "#34275E",
    tertiaryContainer: "#4B3E76",
    onTertiaryContainer: "#E8DEFF",
    error: "#FFB4AB",
    onError: "#690005",
    errorContainer: "#93000A",
    onErrorContainer: "#FFDAD6",
    background: "#121318",
    onBackground: "#E3E1E9",
    surface: "#111418",
    onSurface: "#E1E2E8",
    surfaceVariant: "#45464F",
    onSurfaceVariant: "#C6C5D0",
    outline: "#90909A",
    outlineVariant: "#45464F",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#E1E2E8",
    inverseOnSurface: "#2E3035",
    inversePrimary: "#4E5C92",
    primaryFixed: "#DCE1FF",
    onPrimaryFixed: "#05164B",
    primaryFixedDim: "#B7C4FF",
    onPrimaryFixedVariant: "#364479",
    secondaryFixed: "#D9E2FF",
    onSecondaryFixed: "#001A43",
    secondaryFixedDim: "#AFC6FF",
    onSecondaryFixedVariant: "#2D4678",
    tertiaryFixed: "#E8DEFF",
    onTertiaryFixed: "#1F1048",
    tertiaryFixedDim: "#CDBDFF",
    onTertiaryFixedVariant: "#4B3E76",
    surfaceDim: "#111418",
    surfaceBright: "#37393E",
    surfaceContainerLowest: "#0B0E13",
    surfaceContainerLow: "#191C20",
    surfaceContainer: "#1D2024",
    surfaceContainerHigh: "#272A2F",
    surfaceContainerHighest: "#32353A",
    green: Const_Colors.green,
    yellow: Const_Colors.yellow,
    red: Const_Colors.red,
  },
};
